### ISSUE TITLE
Create README.md file

### ISSUE THREAD

**Issue by just-injoey** [just-injoey/Cryptogyaan#1]
Create a README.md file which consists,
- short description about the project
- Modules to be installed
- Set-up

**Comment by rexdivakar** [comment]
Hey @just-injoey i would like to work on this

**Comment by just-injoey** [comment]
> Hey @just-injoey i would like to work on this

Go ahead

**Comment by rexdivakar** [comment]
Completed the work, kindly review and PR and approve it. Meanwhile could u please tag me for the issue !!
